"""initial chat schema

Revision ID: 77902d4ac728
Revises: 
Create Date: 2026-07-24 13:23:45.381088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77902d4ac728'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('buyer_id', sa.String(length=64), nullable=False),
    sa.Column('seller_id', sa.String(length=64), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'buyer_id', name='uq_product_buyer')
    )
    op.create_index('ix_conversation_buyer', 'conversations', ['buyer_id'], unique=False)
    op.create_index('ix_conversation_product', 'conversations', ['product_id'], unique=False)
    op.create_index('ix_conversation_seller', 'conversations', ['seller_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('message_type', sa.Enum('text', 'image', 'video', 'audio', 'file', name='message_type'), nullable=False),
    sa.Column('status', sa.Enum('sent', 'delivered', 'seen', name='message_status'), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_message_conversation', 'messages', ['conversation_id'], unique=False)
    op.create_index('ix_message_sender', 'messages', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_message_sender', table_name='messages')
    op.drop_index('ix_message_conversation', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_conversation_seller', table_name='conversations')
    op.drop_index('ix_conversation_product', table_name='conversations')
    op.drop_index('ix_conversation_buyer', table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
